FROM maven:3.8.1-openjdk-16 as build
COPY broadcasting-1.0-SNAPSHOT.jar /tmp/
RUN mvn install:install-file -Dfile=/tmp/broadcasting-1.0-SNAPSHOT.jar -DgroupId=org.dbsim.broadcasting -DartifactId=broadcasting -Dversion=1.0-SNAPSHOT -Dpackaging=jar
WORKDIR /app
COPY pom.xml .
COPY /src ./src
RUN mvn clean package

FROM openjdk:17-slim
COPY --from=build /app/target/*.jar /app.jar
CMD ["java", "-jar", "/app.jar"]