FROM maven:3.8.1-openjdk-16 as build
WORKDIR /app
COPY pom.xml .
COPY /src ./src
RUN mvn clean package

FROM openjdk:17-slim
COPY --from=build /app/target/*.jar /app.jar
CMD ["java", "-jar", "/app.jar"]