package org.dbsim.node.enums;

public enum DBEventType {
    DATABASE_CREATED,
    DATABASE_DELETED,
    COLLECTION_CREATED,
    COLLECTION_DELETED,
    COLLECTION_UPDATED,
    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    DOCUMENT_DELETED,
    INDEX_CREATED,
    INDEX_DELETED,
    USER_CREATED,
    USER_DELETED,
}
